
** Is Mathematics Real?

There are some profound paradoxes involving the reality of abstract
ideas vs. the reality of physical objects.

Scientific exploration has proved that reality is very different
from the appearance of reality presented by our senses.
- Our senses and our brains try to parse reality into macroscopic
  objects existing in locations in 3-dimentional space and persisting
  or changing in time.
- Our best scientific theories suggest that reality consists of
  exquisitely tiny particles which are the excitation of invisible
  fields and that space and time are part of a larger 4-dimentional
  structure (spacetime) which is curved.  And that the "gravity" which
  we think we feel is really just the curvature of spacetime fooling
  our senses.
- The extraordinary 
- Although we've learned an enormous amount about physics, giving us
  technological capabilities which would seem like magic to our
  ancestors, our two most successful fundamental theories of what's
  real, relative and quantum mechanics, contradict one another.  Both
  have been verified to an extraordinary level of precision, yet they
  disagree about the nature of reality.
   
The idea that Mathematics and other abstractions exist in a realm
separate from physical reality is part of the [[https://en.wikipedia.org/wiki/Theory_of_forms][Theory of Forms]]
introduced by Greek Mathematicians more than 2000 years ago.
According to this viewpoint Ideal Forms exist timelessly in a realm
separate from physical reality.  The human powers of imagination and
reason allow us to explore this realm and learn about the properties
of and relationships among these forms but we are merely discovering
these things, not inventing them.

Many social scientists reject the [[https://en.wikipedia.org/wiki/Theory_of_forms][Theory of Forms]] and instead insist
that Mathematics is an arbitrary invention of human beings within
specific human cultures, differing in the same way that human
languages differ.  This seems more reasonable and less mystical than
the Theory of Forms!  However, every time mathematical systems which
had developed independently in different cultures have come together,
e.g. when European mathematics encountered South Asian mathematics and
later when it encountered Mayan Mathematics, it all fit together
perfectly.  This is very unlike different languages where translation
is always imperfect.

Some biologists insist that Mathematics is simply a projection of how
Evolution has designed our brains to parse reality, and that different
brain organizations would have a different "Mathematics" or none at
all.  By this view, if we were to meet aliens from another star systems,
we would not agree on mathematics.  And since all of our science is
formulated as mathematical models, we wouldn't agree on any of our
scientific understandings either!  What do you think?
