* On Computing

What is Computing?

You may have been exposed to Computer Programming, whether in the form of the
current craze to learn /Coding/ or through a serious course of study or even as
your profession. If so, you probably have an idea of what computing is. It's
highly likely, however, that what you know is one or two of the weaker
[[https://www.info.ucl.ac.be/~pvr/paradigms.html][Programming Paradigms]], and you've probably missed most of the really powerful
ones - especially metaprogramming!

I'm creating some materials for learning Computer Basics and Computing Magic at
/warp speed/. I invite you to study these materials for your own benefit and I
would be delighted if you were to help make these materials better!

- [[https://gregdavidson.github.io/on-computing/what-computers-are/][What Computers Are]] -- Bits to Bytes to Words to Simple Data Structures
- [[https://gregdavidson.github.io/on-computing/composites.org][Composite Data Structures]] -- Complex Data Structures
- [[https://github.com/GregDavidson/computing-magic][Computing Magic]] -- It feels like magic, when you know the secrets!
- [[https://github.com/GregDavidson/on-lisp][On Lisp]] -- Paul Graham's Secret for [[http://www.paulgraham.com/avg.html][Beating The Averages]]
- [[https://github.com/GregDavidson/C-By-Example][C By Example]] -- Reach out and touch the machine!

/This repository is intended to be a gateway to a lot of important materials,
linked by the documents here. If you explore these materials, please share your
experience, through direct communication, by posting Issues, or etc. Please
suggest improvements!/
